server.port=8084
spring.application.name=notification-service
spring.data.mongodb.uri=mongodb://admin:password@notification-db:27017/notification_db?authSource=admin
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=notification-group
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
