server.port=8083
spring.application.name=ticket-service
spring.datasource.url=jdbc:postgresql://ticket-db:5432/ticket_service_db
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.kafka.bootstrap-servers=kafka:9092
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
